[versions]
# Mod Properties
mod-version = "0.4.0"

# Minecraft
minecraft = "1.21.11"
yarn-mappings = "1.21.11+build.3"
fabric-loader = "0.18.2"
loom = "1.14-SNAPSHOT"

# Dependencies
meteor = "1.21.11-SNAPSHOT"
baritone = "1.21.10-SNAPSHOT"
orbit = "0.2.4"
starscript = "0.2.5"

# SeedFinding
cubiomes = "1.22.3"
mc-core = "1.210.0"
mc-math = "ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91"
mc-seed = "1ead6fcefe7e8de4b3d60cd6c4e993f1e8f33409"
mc-noise = "7e3ba65e181796c4a2a1c8881d840b2254b92962"
mc-biome = "41a42cb9019a552598f12089059538853e18ec78"
mc-terrain = "b4246cbd5880c4f8745ccb90e1b102bde3448126"
mc-feature = "919b7e513cc1e87e029a9cd703fc4e2dc8686229"

# Other
seedcrackerxApi = "2.10.1"

[libraries]
# Minecraft
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Meteor
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }
baritone = { module = "meteordevelopment:baritone", version.ref = "baritone" }
orbit = { module = "meteordevelopment:orbit", version.ref = "orbit" }
starscript = { module = "org.meteordev:starscript", version.ref = "starscript" }

# SeedFinding - Cubiomes (multi-platform)
cubiomes-main = { module = "dev.duti.acheong:cubiomes", version.ref = "cubiomes" }
cubiomes-linux64 = { module = "dev.duti.acheong:cubiomes", version.ref = "cubiomes" }
cubiomes-osx = { module = "dev.duti.acheong:cubiomes", version.ref = "cubiomes" }
cubiomes-windows64 = { module = "dev.duti.acheong:cubiomes", version.ref = "cubiomes" }

# SeedFinding - MC libs
mc-math = { module = "com.seedfinding:mc_math", version.ref = "mc-math" }
mc-seed = { module = "com.seedfinding:mc_seed", version.ref = "mc-seed" }
mc-core = { module = "com.seedfinding:mc_core", version.ref = "mc-core" }
mc-noise = { module = "com.seedfinding:mc_noise", version.ref = "mc-noise" }
mc-biome = { module = "com.seedfinding:mc_biome", version.ref = "mc-biome" }
mc-terrain = { module = "com.seedfinding:mc_terrain", version.ref = "mc-terrain" }
mc-feature = { module = "com.seedfinding:mc_feature", version.ref = "mc-feature" }

# SeedcrackerX
seedcrackerx-api = { group = "com.github.19MisterX98.SeedcrackerX", name = "seedcrackerx-api", version.ref = "seedcrackerxApi" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
